services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true